resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      products:
        base-config: defecto

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IP_ADDR:http://127.0.0.1:9100}
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
            - openid
            - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: ${IP_ADDR:http://127.0.0.1:9100}
  cloud:
    gateway:
      mvc:
        routes:
        - id: msvc-oauth
          uri: lb://msvc-oauth
          predicates:
          - Path=/api/security/**
          filters:
          - StripPrefix=2
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
          - Path=/api/users/**
          filters:
          - StripPrefix=2
        # - id: msvc-products
        #   uri: lb://msvc-products
        #   predicates:
        #   - Path=/api/products/**
          # - Header=token, \d+
          # - Header=token, 12345
          # - Method=GET, POST
          # - Query=color, verde
          # - Cookie=color, azul
          # - Header=Content-Type, application/json
          # filters:
          # - name: CircuitBreaker
          #   args:
          #     name: products
          #     statusCodes: 500
          #     fallbackUri: forward:/api/items/5
          # - StripPrefix=2
          # - name: SampleCookie
          #   args:
          #     message: Hola mi mensaje personalizado para productos
          #     name: user
          #     value: Juan
          # - EjemploCookie=Hola mi mensaje personalizado para productos, user, Juan
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
          - Path=/api/items/**
          filters:
          - StripPrefix=2
          # - AddRequestHeader=token-request, holamundo
          # - AddResponseHeader=token-response, adiosmundo
          # - AddRequestParameter=name, Jose
          # - SetResponseHeader=Content-Type, text/plain